version: '3'
services:
  server:
      build: ./server
      volumes:
        - "./server:/usr/src/server"
      ports:
        - "8080:8080"
  app:
      build: ./app
      depends_on:
        - server
      volumes:
        - "./app:/usr/src/app"
